version: 2.1
commands:
  install_deps:
    steps:
      - run:
          name: Install dependencies
          command: |
            npm install

jobs:
  ci-build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout 
      - install_deps
      - run:
          name: run tests
          command: |
            npm run unit-tests
  intergration-test:
    docker:
      - image: circleci/node:lts
      - image: mongo:4.0
    environment:
      APP_PORT: 4000
    steps:
      - checkout
  sast:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: 
          name: Install NodeJsScan
          command: |
            sudo apt update
            sudo apt install python3-pip
            pip3 install nodejsscan
      - run: 
          name: Run NodeJsScan
          command: |
            nodejsscan -d ./ -o sast-output.json
      - store_artifacts: sast-output.json
      - run:
          name: Parse sast report
          command: |
            exit $(cat sast-output.json | jq .total_count.sec)
  pack:
    docker:
      - image: circleci/node:lts
    environment:
      NODE_ENV: production
    steps:
      - checkout
      - install_deps
      - store_artifacts:
          path: ./

workflows:
  build-and-packge:
    jobs:
      - ci-build
      - intergration-test:
          requires:
            - ci-build
      - sast:
          requires:
            - ci-build
      - pack:
          requires:
            - ci-build
          filters:
            branches:
              only:
                - master
            